"""remove_manager_id_from_employees

Revision ID: 0aa4ff5c2629
Revises: 9dcb8f314760
Create Date: 2026-07-11 00:51:16.673751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa4ff5c2629'
down_revision: Union[str, Sequence[str], None] = '9dcb8f314760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_departments_manager', 'departments', 'employees', ['manager_employee_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('employees_manager_id_fkey'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('employees_manager_id_fkey'), 'employees', 'employees', ['manager_id'], ['id'])
    op.drop_constraint('fk_departments_manager', 'departments', type_='foreignkey')
    # ### end Alembic commands ###
