"""Update position skills model

Revision ID: 38ab1d56fa57
Revises: 6fda1ec3d967
Create Date: 2026-07-26 12:27:33.019817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38ab1d56fa57'
down_revision: Union[str, Sequence[str], None] = '6fda1ec3d967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_skills', sa.Column('required_skill_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='skilllevel'), nullable=False))
    op.add_column('position_skills', sa.Column('importance', sa.Integer(), nullable=False))
    op.drop_column('position_skills', 'required_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_skills', sa.Column('required_level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('position_skills', 'importance')
    op.drop_column('position_skills', 'required_skill_level')
    # ### end Alembic commands ###
