"""align_employee_skills_and_unique_index

Revision ID: 45722b9a247f
Revises: 7d075b5a2b14
Create Date: 2026-07-11 05:33:10.720285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45722b9a247f'
down_revision: Union[str, Sequence[str], None] = '7d075b5a2b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.create_unique_constraint(None, 'skills', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    # ### end Alembic commands ###
