"""add_skill_level_enum_and_position_skills

Revision ID: 7d075b5a2b14
Revises: f77b3ccc919f
Create Date: 2026-07-11 05:14:52.238768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d075b5a2b14'
down_revision: Union[str, Sequence[str], None] = 'f77b3ccc919f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_skills',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id', 'skill_id')
    )
    op.alter_column('employee_skills', 'level',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='skilllevel'),
               existing_nullable=True)
    op.drop_constraint(op.f('employee_skills_skill_id_fkey'), 'employee_skills', type_='foreignkey')
    op.drop_constraint(op.f('employee_skills_employee_id_fkey'), 'employee_skills', type_='foreignkey')
    op.create_foreign_key(None, 'employee_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employee_skills', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('skills_name_key'), 'skills', type_='unique')
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.create_unique_constraint(op.f('skills_name_key'), 'skills', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'employee_skills', type_='foreignkey')
    op.drop_constraint(None, 'employee_skills', type_='foreignkey')
    op.create_foreign_key(op.f('employee_skills_employee_id_fkey'), 'employee_skills', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(op.f('employee_skills_skill_id_fkey'), 'employee_skills', 'skills', ['skill_id'], ['id'])
    op.alter_column('employee_skills', 'level',
               existing_type=sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='skilllevel'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_table('position_skills')
    # ### end Alembic commands ###
