"""replace work and personal email with email

Revision ID: 8f85b74480c6
Revises: 88f667b8877b
Create Date: 2026-07-19 07:08:32.923488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f85b74480c6'
down_revision: Union[str, Sequence[str], None] = '88f667b8877b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('email', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('employees_work_email_key'), 'employees', type_='unique')
    op.create_unique_constraint(None, 'employees', ['phone'])
    op.create_unique_constraint(None, 'employees', ['email'])
    op.drop_column('employees', 'personal_email')
    op.drop_column('employees', 'work_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('work_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('personal_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_constraint(None, 'employees', type_='unique')
    op.create_unique_constraint(op.f('employees_work_email_key'), 'employees', ['work_email'], postgresql_nulls_not_distinct=False)
    op.drop_column('employees', 'email')
    # ### end Alembic commands ###
