"""update position skills

Revision ID: f2908fc365d4
Revises: 1e2cc2ec63e7
Create Date: 2026-08-30 18:23:44.855541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2908fc365d4'
down_revision: Union[str, Sequence[str], None] = '1e2cc2ec63e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('position_skills', 'short_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('position_skills', 'importance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_skills', sa.Column('importance', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('position_skills', 'short_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
