"""remove_manager_employee_id_from_departments

Revision ID: f77b3ccc919f
Revises: 0aa4ff5c2629
Create Date: 2026-07-11 00:58:41.433288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f77b3ccc919f'
down_revision: Union[str, Sequence[str], None] = '0aa4ff5c2629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_departments_manager'), 'departments', type_='foreignkey')
    op.drop_column('departments', 'manager_employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('manager_employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_departments_manager'), 'departments', 'employees', ['manager_employee_id'], ['id'])
    # ### end Alembic commands ###
